USE [master]
GO
/****** Object:  Database [FrankiesHotel_UserDB]    Script Date: 3/4/2024 3:00:47 PM ******/
CREATE DATABASE [FrankiesHotel_UserDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FrankiesHotel_UserDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FrankiesHotel_UserDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FrankiesHotel_UserDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\FrankiesHotel_UserDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FrankiesHotel_UserDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET RECOVERY FULL 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET  MULTI_USER 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET QUERY_STORE = OFF
GO
USE [FrankiesHotel_UserDB]
GO
/****** Object:  Table [dbo].[Application]    Script Date: 3/4/2024 3:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Application](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](max) NULL,
 CONSTRAINT [PK_Application] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Company]    Script Date: 3/4/2024 3:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Company](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NULL,
	[Description] [nvarchar](max) NULL,
 CONSTRAINT [PK_Company] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Role]    Script Date: 3/4/2024 3:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Role](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NULL,
	[Description] [nvarchar](max) NULL,
 CONSTRAINT [PK_Roles] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[User]    Script Date: 3/4/2024 3:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](50) NULL,
	[LastName] [nvarchar](50) NULL,
	[Gender] [nchar](10) NULL,
	[Username] [nvarchar](50) NULL,
	[Password] [nvarchar](50) NULL,
	[Email] [nvarchar](100) NULL,
	[RoleId] [int] NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserApplication]    Script Date: 3/4/2024 3:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserApplication](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[ApplicationId] [int] NULL,
 CONSTRAINT [PK_UserApplication] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserRole]    Script Date: 3/4/2024 3:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserRole](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[UserId] [int] NULL,
	[RoleId] [int] NULL,
 CONSTRAINT [PK_UserRole] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Zone]    Script Date: 3/4/2024 3:00:49 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Zone](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[RoleId] [nchar](10) NULL,
	[Name] [nchar](10) NULL,
 CONSTRAINT [PK_Zone] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[User]  WITH CHECK ADD  CONSTRAINT [FK_User_Role] FOREIGN KEY([RoleId])
REFERENCES [dbo].[Role] ([Id])
GO
ALTER TABLE [dbo].[User] CHECK CONSTRAINT [FK_User_Role]
GO
ALTER TABLE [dbo].[UserApplication]  WITH CHECK ADD  CONSTRAINT [FK_UserApplication_Application] FOREIGN KEY([ApplicationId])
REFERENCES [dbo].[Application] ([Id])
GO
ALTER TABLE [dbo].[UserApplication] CHECK CONSTRAINT [FK_UserApplication_Application]
GO
ALTER TABLE [dbo].[UserApplication]  WITH CHECK ADD  CONSTRAINT [FK_UserApplication_User] FOREIGN KEY([UserId])
REFERENCES [dbo].[User] ([Id])
GO
ALTER TABLE [dbo].[UserApplication] CHECK CONSTRAINT [FK_UserApplication_User]
GO
USE [master]
GO
ALTER DATABASE [FrankiesHotel_UserDB] SET  READ_WRITE 
GO
